# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# https://cloud.tencent.com/developer/article/1742812

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication


class Ui_test(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(620, 542)
        self.label1 = QtWidgets.QLabel(test)
        self.label1.setGeometry(QtCore.QRect(250, 330, 84, 21))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(test)
        self.label2.setGeometry(QtCore.QRect(100, 220, 84, 21))
        self.label2.setObjectName("label2")

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "Form"))
        self.label1.setText(_translate("test", "TextLabel"))
        self.label2.setText(_translate("test", "TextLabel"))


class MyDesiger(QMainWindow, Ui_test):
  def __init__(self, parent=None):
    super(MyDesiger, self).__init__(parent)
    self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ui = MyDesiger()
    ui.show()
    sys.exit(app.exec_())